version: '3'

services:
  postgres:
    image: postgres:13.6-alpine
    container_name: spring_cloud_postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh