server:
  port: 9999

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
          filters:
            - RewritePath=/billing/(?<path>.*), /$\{path}
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<path>.*), /$\{path}
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
          filters:
            - RewritePath=/delivery/(?<path>.*), /$\{path}
      filter:
        retry:
          enabled: true
