server:
  port: 8387

spring:
  config:
    import: optional:configserver:http://localhost:8585
  cloud:
    config:
      uri: http://localhost:8585
      discovery:
        enabled: true
    loadbalancer:
      enabled: true
  application:
    name: delivery-service

management:
  endpoints:
    web:
      exposure:
        include: env,refresh
eureka:
  client:
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka